import { prisma } from "./client.js";

async function main() {
    await prisma.product.createMany({
      data: [
        { name: "Toyota Corolla", price: 23000, invoice_id: null },
        { name: "Honda Civic", price: 25000, invoice_id: null },
        { name: "Ford Focus", price: 21000, invoice_id: null },
        { name: "Chevrolet Cruze", price: 22000, invoice_id: null },
        { name: "Volkswagen Golf", price: 24000, invoice_id: null },
        { name: "Nissan Sentra", price: 20000, invoice_id: null },
        { name: "Hyundai Elantra", price: 21500, invoice_id: null },
        { name: "Kia Rio", price: 18000, invoice_id: null },
        { name: "BMW Serie 3", price: 42000, invoice_id: null },
        { name: "Audi A4", price: 40000, invoice_id: null },
        { name: "Mercedes-Benz C200", price: 45000, invoice_id: null },
        { name: "Peugeot 208", price: 17000, invoice_id: null },
        { name: "Renault Clio", price: 16000, invoice_id: null },
        { name: "Fiat Argo", price: 15500, invoice_id: null },
        { name: "Jeep Renegade", price: 28000, invoice_id: null },
        { name: "Toyota Yaris", price: 19000, invoice_id: null },
        { name: "Honda Fit", price: 18500, invoice_id: null },
        { name: "Ford Fiesta", price: 17500, invoice_id: null },
        { name: "Chevrolet Onix", price: 16000, invoice_id: null },
        { name: "Volkswagen Polo", price: 19500, invoice_id: null },
        { name: "Nissan Versa", price: 18500, invoice_id: null },
        { name: "Hyundai Accent", price: 20000, invoice_id: null },
        { name: "Kia Cerato", price: 21000, invoice_id: null },
        { name: "BMW X1", price: 38000, invoice_id: null },
        { name: "Audi Q3", price: 37000, invoice_id: null },
        { name: "Mercedes-Benz GLA200", price: 39000, invoice_id: null },
        { name: "Peugeot 3008", price: 31000, invoice_id: null },
        { name: "Renault Captur", price: 25000, invoice_id: null },
        { name: "Fiat Pulse", price: 21000, invoice_id: null },
        { name: "Jeep Compass", price: 33000, invoice_id: null },
        { name: "Toyota Hilux", price: 42000, invoice_id: null },
        { name: "Ford Ranger", price: 41000, invoice_id: null },
        { name: "Chevrolet S10", price: 40000, invoice_id: null },
        { name: "Volkswagen Amarok", price: 43000, invoice_id: null },
        { name: "Nissan Frontier", price: 39500, invoice_id: null },
        { name: "Hyundai Santa Fe", price: 37000, invoice_id: null },
        { name: "Kia Sportage", price: 32000, invoice_id: null },
        { name: "BMW X3", price: 50000, invoice_id: null },
        { name: "Audi Q5", price: 51000, invoice_id: null },
        { name: "Mercedes-Benz GLC", price: 52000, invoice_id: null },
        { name: "Peugeot 2008", price: 24000, invoice_id: null },
        { name: "Renault Duster", price: 22000, invoice_id: null },
        { name: "Fiat Toro", price: 28000, invoice_id: null },
        { name: "Jeep Gladiator", price: 48000, invoice_id: null },
        { name: "Toyota RAV4", price: 36000, invoice_id: null },
        { name: "Honda CR-V", price: 35000, invoice_id: null },
        { name: "Ford Escape", price: 33000, invoice_id: null },
        { name: "Chevrolet Equinox", price: 34000, invoice_id: null },
        { name: "Volkswagen Tiguan", price: 35500, invoice_id: null },
        { name: "Nissan X-Trail", price: 34500, invoice_id: null },
        { name: "Hyundai Tucson", price: 32500, invoice_id: null },
        { name: "Kia Sorento", price: 39000, invoice_id: null },
        { name: "BMW X5", price: 65000, invoice_id: null },
        { name: "Audi Q7", price: 67000, invoice_id: null },
        { name: "Mercedes-Benz GLE", price: 69000, invoice_id: null },
        { name: "Peugeot 5008", price: 37000, invoice_id: null },
        { name: "Renault Koleos", price: 36000, invoice_id: null },
        { name: "Fiat 500", price: 17000, invoice_id: null },
        { name: "Jeep Cherokee", price: 45000, invoice_id: null },
        { name: "Toyota Land Cruiser", price: 85000, invoice_id: null },
        { name: "Honda HR-V", price: 28000, invoice_id: null },
        { name: "Ford Edge", price: 44000, invoice_id: null },
        { name: "Chevrolet Tracker", price: 23000, invoice_id: null },
        { name: "Volkswagen T-Cross", price: 22500, invoice_id: null },
        { name: "Nissan Kicks", price: 21500, invoice_id: null },
        { name: "Hyundai Kona", price: 26000, invoice_id: null },
        { name: "Kia Seltos", price: 25500, invoice_id: null },
        { name: "BMW i3", price: 48000, invoice_id: null },
        { name: "Audi e-tron", price: 70000, invoice_id: null },
        { name: "Mercedes-Benz EQC", price: 72000, invoice_id: null },
        { name: "Peugeot e-208", price: 31000, invoice_id: null },
        { name: "Renault Zoe", price: 28000, invoice_id: null },
        { name: "Fiat Panda", price: 15000, invoice_id: null },
        { name: "Jeep Grand Cherokee", price: 60000, invoice_id: null },
        { name: "Toyota Prius", price: 27000, invoice_id: null },
        { name: "Honda Insight", price: 26000, invoice_id: null },
        { name: "Ford Mustang", price: 55000, invoice_id: null },
        { name: "Chevrolet Camaro", price: 57000, invoice_id: null },
        { name: "Volkswagen Passat", price: 30000, invoice_id: null },
        { name: "Nissan Altima", price: 29000, invoice_id: null },
        { name: "Hyundai Sonata", price: 28500, invoice_id: null },
        { name: "Kia Optima", price: 29500, invoice_id: null },
        { name: "BMW Serie 5", price: 60000, invoice_id: null },
        { name: "Audi A6", price: 59000, invoice_id: null },
        { name: "Mercedes-Benz E200", price: 61000, invoice_id: null },
        { name: "Peugeot 301", price: 20000, invoice_id: null },
        { name: "Renault Logan", price: 18500, invoice_id: null },
        { name: "Fiat Cronos", price: 17500, invoice_id: null },
        { name: "Jeep Wrangler", price: 47000, invoice_id: null },
        { name: "Toyota Supra", price: 65000, invoice_id: null },
        { name: "Honda Accord", price: 31000, invoice_id: null },
        { name: "Ford Mondeo", price: 30500, invoice_id: null },
        { name: "Chevrolet Malibu", price: 29500, invoice_id: null },
        { name: "Volkswagen Jetta", price: 28000, invoice_id: null },
        { name: "Nissan Maxima", price: 35000, invoice_id: null },
        { name: "Hyundai Veloster", price: 27000, invoice_id: null },
        { name: "Kia Stinger", price: 42000, invoice_id: null },
        { name: "BMW Serie 7", price: 90000, invoice_id: null },
        { name: "Audi A8", price: 95000, invoice_id: null },
        { name: "Mercedes-Benz S500", price: 98000, invoice_id: null },
      ],
      skipDuplicates: true,
    });
}
main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());